# github action to buld and deploy to FTP
name: Deploy To Somee DEV

on:
  push:
    branches:
      - calidad
#  pull_request:
#    branches:
#      - calidad
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ›Žï¸ Checkout Repository
        uses: actions/checkout@v3

      - name: ðŸ”§ Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
          
      - name: ðŸ”„ Replace Connection String in appsettings.json
        run: |
            jq '.ConnectionStrings.ToshiDBContext = "${{ secrets.CONNECTION_STRING }}"' ./Toshi.Backend.API/appsettings.json > temp.json && mv temp.json ./Toshi.Backend.API/appsettings.json

      - name: ðŸ”„ Replace JetSettings Key in appsettings.json
        run: |
            jq '.JwtSettings.Key = "${{ secrets.JWT_SETTINGS_KEY }}"' ./Toshi.Backend.API/appsettings.json > temp.json && mv temp.json ./Toshi.Backend.API/appsettings.json

      - name: ðŸ“¦ Restore Dependencies
        run: dotnet restore ./Toshi.Backend.API/Toshi.Backend.API.csproj
      
      - name: ðŸ“¦ Build
        run: dotnet build ./Toshi.Backend.API/Toshi.Backend.API.csproj

      - name: ðŸš€ Build and Publish
        run: dotnet publish ./Toshi.Backend.API/Toshi.Backend.API.csproj -c Release -o ./publish
#        run: dotnet publish ./Toshi.Backend.API/Toshi.Backend.API.csproj --configuration Release --output ./publish

      - name: ðŸ“‚ Deploy via FTP
        run: |
          sudo apt-get install -y lftp
          lftp -e "
            open -u ${{ secrets.ftp_username }},${{ secrets.ftp_password }} ${{ secrets.ftp_server }};
            mirror -R ./publish/ ${{ secrets.FTP_REMOTE_PATH_DEV }};
            bye
          "
